services:
  # 1. Django API Web Service
  - type: web
    name: chem-backend-api
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: starter
    preDeployCommand: "python manage.py migrate"
    envVars:
      - fromGroup: chem-secrets

  # 2. Celery Worker
  - type: worker
    name: chem-celery-worker
    env: docker
    dockerContext: .
    dockerCommand: celery -A config worker --loglevel=info
    plan: starter
    envVars:
      - fromGroup: chem-secrets

  # 3. Celery Beat (Scheduler)
  - type: worker
    name: chem-celery-beat
    env: docker
    dockerContext: .
    dockerCommand: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    plan: starter
    envVars:
      - fromGroup: chem-secrets

  # 4. Kafka Sentiment Consumer
  - type: worker
    name: chem-kafka-consumer
    env: docker
    dockerContext: .
    dockerCommand: python consumer_worker.py
    plan: starter
    envVars:
      - fromGroup: chem-secrets

  # 5. Platform Kafka Consumer
  - type: worker
    name: chem-platform-consumer
    env: docker
    dockerContext: .
    dockerCommand: python platform_consumer.py
    plan: starter
    envVars:
      - fromGroup: chem-secrets
