# Generated by Django 6.0.2 on 2026-03-06 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=50)),
                ('channel_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_url', models.URLField(max_length=500)),
                ('profile_picture', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('followers', models.BigIntegerField(default=0)),
                ('following', models.BigIntegerField(default=0)),
                ('posts_count', models.IntegerField(default=0)),
                ('total_likes', models.BigIntegerField(default=0)),
                ('total_comments', models.BigIntegerField(default=0)),
                ('total_shares', models.BigIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('views', models.BigIntegerField(default=0)),
                ('subscribers', models.BigIntegerField(default=0)),
                ('impressions', models.BigIntegerField(default=0)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='platforms.platform')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_post_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('post_url', models.URLField(max_length=500)),
                ('media_urls', models.JSONField(default=list)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='platforms.platform')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFetchTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('stats_collected', models.JSONField(default=dict)),
                ('posts_collected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_tasks', to='platforms.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddPlatform',
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['user', 'is_active'], name='platforms_p_user_id_7c68a9_idx'),
        ),
        migrations.AddIndex(
            model_name='platform',
            index=models.Index(fields=['name'], name='platforms_p_name_c912ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('user', 'name', 'channel_id')},
        ),
        migrations.AddIndex(
            model_name='channelstats',
            index=models.Index(fields=['platform', 'period_start'], name='platforms_c_platfor_6ed3a4_idx'),
        ),
        migrations.AddIndex(
            model_name='channelstats',
            index=models.Index(fields=['platform', 'period_end'], name='platforms_c_platfor_984792_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['platform', 'published_at'], name='platforms_c_platfor_1f00b4_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['sentiment_label'], name='platforms_c_sentime_ae9c9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channelpost',
            unique_together={('platform', 'platform_post_id')},
        ),
        migrations.AddIndex(
            model_name='platformfetchtask',
            index=models.Index(fields=['user', 'status'], name='platforms_p_user_id_b179d6_idx'),
        ),
        migrations.AddIndex(
            model_name='platformfetchtask',
            index=models.Index(fields=['created_at'], name='platforms_p_created_b7a4db_idx'),
        ),
    ]
