from django.urls import path
from .views import (
    SignupView, LoginView, LogoutView, VerifyAuth, ProfileView, 
    ChangePasswordView, DeleteAccountView, DeactivateAccountView, 
    Enable2FAView, Verify2FAView, Disable2FAView, LoginVerify2FAView, 
    SecurityQuestionListView, SetupSecurityQuestionsView, Check2FAStatusView,
    AccountMemberListView, AccountRoleListView, UpdateMemberRoleView, RemoveMemberView,
    InviteMemberView, AcceptInvitationView, InvitationDetailView, ProcessInvitationView,
    AvatarUploadView, ForgotPasswordView, ResetPasswordView, SocialAuthView
)

urlpatterns = [
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("social-auth/", SocialAuthView.as_view(), name="social-auth"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("verify/", VerifyAuth.as_view(), name="verifyauth"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("avatar-upload/", AvatarUploadView.as_view(), name="avatar-upload"),
    path("change-password/", ChangePasswordView.as_view(), name="change-password"),
    path("delete/", DeleteAccountView.as_view(), name="delete-account"),
    path("deactivate/", DeactivateAccountView.as_view(), name="deactivate-account"),
    path("2fa/enable/", Enable2FAView.as_view(), name="enable-2fa"),
    path("2fa/verify/", Verify2FAView.as_view(), name="verify-2fa"),
    path("2fa/disable/", Disable2FAView.as_view(), name="disable-2fa"),
    path("2fa/login-verify/", LoginVerify2FAView.as_view(), name="login-verify-2fa"),
    path("2fa/check-status/", Check2FAStatusView.as_view(), name="check-2fa-status"),
    path("security-questions/", SecurityQuestionListView.as_view(), name="security-questions"),
    path("setup-security-questions/", SetupSecurityQuestionsView.as_view(), name="setup-security-questions"),
    path("members/", AccountMemberListView.as_view(), name="account-members"),
    path("roles/", AccountRoleListView.as_view(), name="account-roles"),
    path("members/update-role/", UpdateMemberRoleView.as_view(), name="update-member-role"),
    path("members/remove/<int:member_id>/", RemoveMemberView.as_view(), name="remove-member"),
    path("members/invite/", InviteMemberView.as_view(), name="invite-member"),
    path("members/accept/<str:token>/", AcceptInvitationView.as_view(), name="accept-member"),
    path("members/invitation-details/<str:token>/", InvitationDetailView.as_view(), name="invitation-details"),
    path("members/process-invitation/", ProcessInvitationView.as_view(), name="process-invitation"),
]
